/*
 *  TCC runtime library for 32-bit PowerPC (Apple Mach-O).
 *
 *  Provides the libgcc helpers that the PPC backend emits calls to
 *  but that aren't supplied by the system. Currently just one:
 *  __floatundidf (unsigned long long -> double) which gen_cvt_itof1
 *  in tccgen.c reaches for, but Apple's libSystem doesn't export.
 *
 *  Copying and distribution of this file, with or without modification,
 *  are permitted in any medium without royalty provided the copyright
 *  notice and this notice are preserved. This file is offered as-is,
 *  without any warranty.
 */

/* Convert by splitting into two 32-bit unsigned halves so we don't
 * recursively reach for __floatundidf. (uint32 -> double goes through
 * gen_cvt_itof's magic-constant inline expansion, no libcall.) */
double __floatundidf(unsigned long long x)
{
    double hi = (double)(unsigned int)(x >> 32);
    double lo = (double)(unsigned int)x;
    return hi * 4294967296.0 + lo;
}

/* ----------------------------------------------------------------- */
/* Minimal "crt1" replacement for executables produced by ppc-macho.c.
 *
 * Apple's standard /usr/lib/crt1.o sets up several libSystem globals
 * before main runs (most importantly _NXArgc, _NXArgv, environ).
 * Without them, libSystem functions that touch process state (printf
 * via stdout, getenv via environ, malloc's heap) deref invalid
 * pointers and crash.
 *
 * We cover the bare minimum here: pull argc/argv/envp from the kernel-
 * provided register values and stash them into libSystem globals.
 * That's enough for printf/getenv/malloc to work; we don't yet
 * replicate the dyld-image-state and key-manager init that crt1 also
 * does.
 *
 * The exec entry point (LC_UNIXTHREAD srr0) jumps to a tiny shim
 * generated by exe_emit_crt_shim() in ppc-macho.c which handles
 * stack alignment and then `bl __tcc_start_main`. We expect the shim
 * to pass argc/argv/envp in r3/r4/r5 (the kernel hands them to the
 * entry point that way).
 */

extern int    _NXArgc;
extern char **_NXArgv;
extern char **environ;
extern int    main(int argc, char **argv, char **envp);
extern void   _exit(int status);

void __tcc_start_main(int argc, char **argv, char **envp)
{
    _NXArgc  = argc;
    _NXArgv  = argv;
    environ  = envp;
    _exit(main(argc, argv, envp));
}
